services:
  - type: web
    name: badmintonshop
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: frankfurt
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 80
      - key: APP_NAME
        value: BadmintonShop
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 4000
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: LOG_CHANNEL
        value: stderr
